### PR TITLE
AP-TWILIO-TAP change field types on tap-twilio

### PR DESCRIPTION
**Pull request by RobinSindberg**
## Problem

There are a few issues with the tap twilio tables. Main points below.

## Proposed changes

1) changing three field types from "string" to "object" to allow for parse_json

In separate PRs:
2) changing replication_method for four streams from INCREMENTAL to FULL_TABLE
3) adding missing fields to some tables 
4) backfill missing data on EVENTS and TASKS 

## Types of changes

What types of changes does your code introduce to PipelineWise?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] MAYBE Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

- [x] Description above provides context of the change
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Unit tests for changes (not needed for documentation changes)
- [x] CI checks pass with my changes
- [ ] Bumping version in `setup.py` is an individual PR and not mixed with feature or bugfix PRs
- [ ] Commit message/PR title starts with `[AP-NNNN]` (if applicable. AP-NNNN = JIRA ID)
- [-] Branch name starts with `AP-NNN` (if applicable. AP-NNN = JIRA ID)
- [ ] Commits follow "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)"
- [ ] Relevant documentation is updated including usage instructions

### CODE REVIEW

**Review by tibortezsla — APPROVED** [review]
Looks good! 🚀

**Review by tibortezsla — CHANGES_REQUESTED** [review]
Tried to run the tap locally, but failed 😢 
Will investigate if the error is in front of the screen or about what's on it! Coming back soon with an answer!

**Comment by tibortezsla** [comment]
Unfortunately it's the tap, it cannot convert those fields to `object`, nor `array`.

**Comment by koszti** [comment]
Please use the following type:

```
      "type": [
        "null",
        "object",
        "array",
      ]
```

If the API sends the object as JSON strings then you can try to parse it before passing the value by `json.loads(stringified_json_response)`

**Comment by tibortezsla** [comment]
> We can extend the schema and add `ARRAY` to the list of types:
> 
> ```
>       "type": [
>         "null",
>         "object",
>         "array",
>       ]
> ```
> 
> If the API sends the object as JSON strings then you we can try to parse it before passing the value by `json.loads(stringified_json_response)`

what does the list of `type`s there mean? It's `null`, if not, then try it as an `object`, if it cannot be parsed like that, try it as an `array`?

**Comment by koszti** [comment]
this PR is covered and merged by https://github.com/transferwise/pipelinewise-tap-twilio/pull/20
Closing this.

**Pull request closed without merging**
